#ifndef PROCESS_LOADER_H
#define PROCESS_LOADER_H
#include "process.h"
#define PROGRAM_SIZE 0x2500
#define PROGRAM_ENTRY 0x20001000
#define STACK_SIZE 0x500
enum LoadResult{
	LOAD_OK=0, LOAD_CANT_READ_ELF_HEADER, LOAD_BAD_SIGNATURE,
	LOAD_BAD_CLASS, LOAD_BAD_BYTE_ORDER, LOAD_BAD_ELF_HEAD_VERSION,
	LOAD_INCOMPATIBLE_OSABI, LOAD_NOT_EXECUTABLE_FILE, LOAD_WRONG_ARCH,
	LOAD_BAD_ELF_VERSION, LOAD_WRONG_ENTRY, LOAD_CANT_READ_PROGRAM_HEADER,
	LOAD_TOO_LARGE, LOAD_CANT_READ
};
enum LoadResult loadProcessFromElfFile(char* filename, struct Process* proc);
#endif