#ifndef PROCESS_LOADER_H
#define PROCESS_LOADER_H
#include "process.h"
#define PROGRAM_SIZE 0x2500
#define PROGRAM_ENTRY 0x20001000
enum LoadELFResult{
	LOAD_ELF_OK=0, LOAD_ELF_CANT_READ_ELF_HEADER, LOAD_ELF_BAD_SIGNATURE,
	LOAD_ELF_BAD_CLASS, LOAD_ELF_BAD_BYTE_ORDER, LOAD_ELF_BAD_ELF_HEAD_VERSION,
	LOAD_ELF_INCOMPATIBLE_OSABI, LOAD_ELF_NOT_EXECUTABLE_FILE, LOAD_ELF_WRONG_ARCH,
	LOAD_ELF_BAD_ELF_VERSION, LOAD_ELF_WRONG_ENTRY, LOAD_ELF_CANT_READ_PROGRAM_HEADER,
	LOAD_ELF_TOO_LARGE, LOAD_ELF_CANT_READ
};
enum LoadELFResult loadProcessFromElfFile(char* filename, struct Process* proc);
#endif